[package]
name = "euler"
version = "0.1.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]

[dependencies]
bdrck_log = "0.3"
bdrck_params = "0.3"
error-chain = "0.10"
glob = "0.2"
itoa = "0.3"
lazy_static = "0.2"
log = "0.3"
num_cpus = "1.3"
rand = "0.3"
rust-gmp = "0.3"
rust-mpfr = "0.1"
