[package]
name = "euler"
version = "0.1.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]

[dependencies]
backtrace = "0.2"
bdrck_log = { path = "/home/ajr/workshop/rust/bdrck/bdrck_log", version = "0.1" }
bdrck_params = { path = "/home/ajr/workshop/rust/bdrck/bdrck_params", version = "0.2" }
glob = "0.2"
log = "0.3"
rand = "0.3"
rust-gmp = "0.3"
