[package]
name = "euler"
version = "0.1.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]

[dependencies]
backtrace = "0.2"
bdrck_params = { path = "/home/ajr/workshop/rust/bdrck/bdrck_params", version = "0.1" }
env_logger = "0.3"
log = "0.3"

[[bin]]
name = "mkprob"
path = "src/tools/mkprob.rs"
